ALTER TABLE GARDEN_COORDINATOR
    ADD COLUMN GardenerID INT NULL UNIQUE,
    ADD CONSTRAINT fk_coordinator_gardener
        FOREIGN KEY (GardenerID) REFERENCES COMMUNITY_GARDENER(GardenerID) ON DELETE SET NULL;

ALTER TABLE SIGNUP_REQUEST
    ADD COLUMN RejectionReason VARCHAR(1000) NULL,
    ADD COLUMN StatusToken CHAR(64) NULL UNIQUE;

ALTER TABLE PLOT_APPLICATION
    ADD COLUMN RejectionReason VARCHAR(1000) NULL;

ALTER TABLE RESOURCE_TXN
    ADD COLUMN RejectionReason VARCHAR(1000) NULL;

CREATE TABLE COORDINATOR_APPLICATION (
    ApplicationID INT AUTO_INCREMENT PRIMARY KEY,
    GardenerID    INT           NOT NULL,
    Shift         VARCHAR(20)   NOT NULL,
    Motivation    VARCHAR(1000) NOT NULL,
    Status        VARCHAR(20)   NOT NULL DEFAULT 'Pending',
    RejectionReason VARCHAR(1000) NULL,
    ReviewedAt    DATETIME      NULL,
    ReviewedBy    INT           NULL,
    RequestedAt   DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_coordinator_application_status (Status, RequestedAt),
    FOREIGN KEY (GardenerID) REFERENCES COMMUNITY_GARDENER(GardenerID) ON DELETE CASCADE,
    FOREIGN KEY (ReviewedBy) REFERENCES SYSTEM_ADMINISTRATOR(AdminID) ON DELETE SET NULL
) ENGINE=InnoDB;
