-- Normalize legacy account rows before relying on Active/Disabled status values.
UPDATE SYSTEM_ADMINISTRATOR SET Status = 'Active' WHERE Status IS NULL OR TRIM(Status) = '';
UPDATE GARDEN_COORDINATOR SET Status = 'Active' WHERE Status IS NULL OR TRIM(Status) = '';
UPDATE COMMUNITY_GARDENER SET Status = 'Active' WHERE Status IS NULL OR TRIM(Status) = '';

ALTER TABLE SYSTEM_ADMINISTRATOR MODIFY Status VARCHAR(20) NOT NULL DEFAULT 'Active';
ALTER TABLE GARDEN_COORDINATOR MODIFY Status VARCHAR(20) NOT NULL DEFAULT 'Active';
ALTER TABLE COMMUNITY_GARDENER MODIFY Status VARCHAR(20) NOT NULL DEFAULT 'Active';
