CREATE TABLE ACCOUNT_ARCHIVE_NOTICE (
    NoticeID   INT AUTO_INCREMENT PRIMARY KEY,
    GardenerID INT           NOT NULL,
    AdminID    INT           NULL,
    Reason     VARCHAR(50)   NOT NULL,
    Details    VARCHAR(1000) NOT NULL,
    CreatedAt  DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_archive_notice_gardener (GardenerID, CreatedAt),
    FOREIGN KEY (GardenerID) REFERENCES COMMUNITY_GARDENER(GardenerID) ON DELETE CASCADE,
    FOREIGN KEY (AdminID) REFERENCES SYSTEM_ADMINISTRATOR(AdminID) ON DELETE SET NULL
) ENGINE=InnoDB;
