-- Add this to an existing HarvestHub database to enable three-strike login lockout.
ALTER TABLE SYSTEM_ADMINISTRATOR
    ADD COLUMN FailedLoginAttempts TINYINT UNSIGNED NOT NULL DEFAULT 0;

ALTER TABLE GARDEN_COORDINATOR
    ADD COLUMN FailedLoginAttempts TINYINT UNSIGNED NOT NULL DEFAULT 0;

ALTER TABLE COMMUNITY_GARDENER
    ADD COLUMN FailedLoginAttempts TINYINT UNSIGNED NOT NULL DEFAULT 0;
